### ISSUE TITLE
Could not import content pack on Graylog 2.1.2

### ISSUE THREAD

**Issue by timtoa** [alias454/graylog-fortinet-content-pack#1]
Below error message pop up while importing the JSON file on Graylog 2.1.2. I am able to import JSON created by juiceman84. Did I miss anything? 

-------------- Error Message --------------
"Could not import content pack
Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information."

**Comment by alias454** [comment]
I will check this on a newer version of graylog once I spin up the newest ova to verify. I can import on an older instance of 1.3.3 though without any issues.

**Comment by alias454** [comment]
@timtoa I did some validation and found there was an issue with the json parameters. I removed the "default_stream": false line and was able to import it into the 2.1.2 ova. Thanks for letting me know.

**Comment by timtoa** [comment]
It works now. Appreciate your effort. Thanks.
