### ISSUE TITLE
Unable to install in Graylog 2.2.2

### ISSUE THREAD

**Issue by oouups** [alias454/graylog-fortinet-content-pack#2]
Import Content Pack
= Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information.

**Comment by alias454** [comment]
Can you try a previous version of the content_pack.json? 

The important bit is this line 
"default_stream": false

https://github.com/alias454/graylog-fortinet-content-pack/tree/a343d1bd0fc63ac83d715209e66e1d416dab6450

**Comment by oouups** [comment]
Hello

Sorry but dosent help

Removinge the line default_stream  doesnt help

Where i found a older version ? Why you not fix it ?

Thank you

Von: alias454 [mailto:notifications@github.com]
Gesendet: Samstag, 25. März 2017 01:10
An: alias454/graylog-fortinet-content-pack
Cc: oouups; Author
Betreff: Re: [alias454/graylog-fortinet-content-pack] Unable to install in Graylog 2.2.2 (#2)


Closed #2<https://github.com/alias454/graylog-fortinet-content-pack/issues/2>.

**Comment by alias454** [comment]
@oouups The link was to an older version of the content_pack. more specifically https://github.com/alias454/graylog-fortinet-content-pack/blob/a343d1bd0fc63ac83d715209e66e1d416dab6450/content_pack.json

i will spin up a 2.2 instance and verify the fix . The problem is I can fix it for the latest version then will have people have troubles with older versions of Graylog. I suppose I could add both versions to the git repo to make it easier.
Regards,

**Comment by oouups** [comment]
Hello and many thx for your reply..

Recomend to publish 2 versions. Because the link to older version i used dosent work also. Same error msg.

PS: removing the line (1197) with content „default_stream“ also not work.


Greetings from switzerland
And many thx for your great job

Von: alias454 [mailto:notifications@github.com]
Gesendet: Montag, 27. März 2017 17:46
An: alias454/graylog-fortinet-content-pack
Cc: oouups; Mention
Betreff: Re: [alias454/graylog-fortinet-content-pack] Unable to install in Graylog 2.2.2 (#2)


@oouups<https://github.com/oouups> The link was to an older version of the content_pack. more specifically https://github.com/alias454/graylog-fortinet-content-pack/blob/a343d1bd0fc63ac83d715209e66e1d416dab6450/content_pack.json

i will spin up a 2.2 instance and verify the fix . The problem is I can fix it for the latest version then will have people have troubles with older versions of Graylog. I suppose I could add both versions to the git repo to make it easier.
Regards,

**Comment by alias454** [comment]
@oouups I downloaded the 2.2.2 ova and was not able to reproduce this when importing the content_pack.json file from the latest.

![forti_utm](https://cloud.githubusercontent.com/assets/10768415/24582694/cdb5f640-16fa-11e7-8040-5a9a14a962e6.PNG)

Try to copy and past the raw contents into a file named content_pack.json on your computer https://raw.githubusercontent.com/alias454/graylog-fortinet-content-pack/master/content_pack.json
