### ISSUE TITLE
automatic key value pair extraction

### ISSUE THREAD

**Issue by SimonGurney** [alias454/graylog-fortinet-content-pack#3]
Hi,

I am seeing extra fields in my extracted messages for each key value pair, i.e. srcip, srcintf ect but cannot find where these are configured to be extracted or how to prevent it?

Thanks,

Simon

**Comment by alias454** [comment]
Hi @SimonGurney, You can search the content pack json file for srcintf etc to find the extractor title, which will look like this -- "title": "Fortinet Origin Interface". You can select a message input on the Graylog system. Once on the inputs page, select manage extractors in the actions menu. Find the title of the extractor you wish to edit and save any changes.

Let me know if you have additional questions.

Regards,
Brandon

**Comment by SimonGurney** [comment]
Hi,

Sorry I think you have misunderstood.  I'm getting 2 fields for every value, one named as you have named it and one matching the original Key Value pair from syslog i.e. srcintf/Origin_Interface, srcip/10.64.20.11, DeviceID/devid.

I can't work out where the second field (given the original name from the KV pair) is coming from as I don't get this on my other syslog inputs.

**Comment by alias454** [comment]
I see what your saying. What version of Graylog are you using? There may have been some changes where Graylog automatically extract fields from Cisco and fortinet devices. Unfortunately, I don't have access to a fortinet device any more so I'm unable to check this. Another thing that might help is if you can provide the input config or look to see if automatic field extraction is checked.

Let me know what you come up with.

Regards,
Brandon

**Comment by SimonGurney** [comment]
Hi Brandon,

You are right, its a default action on the graylog extractors for syslog.  Switching to RAW UDP fixes the issue, but I might have caused it in the first place.  I have some extra extractors if you want me to commit them?

**Comment by alias454** [comment]
Sure that would be great. I've always second guessed my decision to go off book and not use the default field names in my extractors for this. I'm not sure if that would have made a difference or not but I wonder.Glad you got it sorted.

Regards,
Brandon

**Comment by alias454** [comment]
Closing issue
